version: '3'

services:

  app:
    build: .
#    restart: always
    # links: 
    #   - mysqldb:mysqldb
    ports:
      - "80:8080"

  mysqldb:
    image: mysql
    ports:
    - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_PASSWORD: example
    volumes:
      - mysql:/var/lib/mysql
      - mysql_config:/etc/mysql

volumes:
  mysql:
  mysql_config:

